
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model AdminUser
 * 
 */
export type AdminUser = Prisma.AdminUserModel
/**
 * Model Company
 * 
 */
export type Company = Prisma.CompanyModel
/**
 * Model Contact
 * 
 */
export type Contact = Prisma.ContactModel
/**
 * Model Lead
 * 
 */
export type Lead = Prisma.LeadModel
/**
 * Model Project
 * 
 */
export type Project = Prisma.ProjectModel
/**
 * Model Activity
 * 
 */
export type Activity = Prisma.ActivityModel
/**
 * Model StatusDefinition
 * 
 */
export type StatusDefinition = Prisma.StatusDefinitionModel
/**
 * Model ImportBatch
 * 
 */
export type ImportBatch = Prisma.ImportBatchModel
