
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Activity` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Activity
 * 
 */
export type ActivityModel = runtime.Types.Result.DefaultSelection<Prisma.$ActivityPayload>

export type AggregateActivity = {
  _count: ActivityCountAggregateOutputType | null
  _min: ActivityMinAggregateOutputType | null
  _max: ActivityMaxAggregateOutputType | null
}

export type ActivityMinAggregateOutputType = {
  id: string | null
  companyId: string | null
  projectId: string | null
  contactId: string | null
  type: string | null
  date: Date | null
  time: string | null
  performedBy: string | null
  contactPerson: string | null
  description: string | null
  result: string | null
  nextAction: string | null
  nextFollowUp: Date | null
  notes: string | null
  createdAt: Date | null
}

export type ActivityMaxAggregateOutputType = {
  id: string | null
  companyId: string | null
  projectId: string | null
  contactId: string | null
  type: string | null
  date: Date | null
  time: string | null
  performedBy: string | null
  contactPerson: string | null
  description: string | null
  result: string | null
  nextAction: string | null
  nextFollowUp: Date | null
  notes: string | null
  createdAt: Date | null
}

export type ActivityCountAggregateOutputType = {
  id: number
  companyId: number
  projectId: number
  contactId: number
  type: number
  date: number
  time: number
  performedBy: number
  contactPerson: number
  description: number
  result: number
  nextAction: number
  nextFollowUp: number
  notes: number
  createdAt: number
  _all: number
}


export type ActivityMinAggregateInputType = {
  id?: true
  companyId?: true
  projectId?: true
  contactId?: true
  type?: true
  date?: true
  time?: true
  performedBy?: true
  contactPerson?: true
  description?: true
  result?: true
  nextAction?: true
  nextFollowUp?: true
  notes?: true
  createdAt?: true
}

export type ActivityMaxAggregateInputType = {
  id?: true
  companyId?: true
  projectId?: true
  contactId?: true
  type?: true
  date?: true
  time?: true
  performedBy?: true
  contactPerson?: true
  description?: true
  result?: true
  nextAction?: true
  nextFollowUp?: true
  notes?: true
  createdAt?: true
}

export type ActivityCountAggregateInputType = {
  id?: true
  companyId?: true
  projectId?: true
  contactId?: true
  type?: true
  date?: true
  time?: true
  performedBy?: true
  contactPerson?: true
  description?: true
  result?: true
  nextAction?: true
  nextFollowUp?: true
  notes?: true
  createdAt?: true
  _all?: true
}

export type ActivityAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Activity to aggregate.
   */
  where?: Prisma.ActivityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Activities to fetch.
   */
  orderBy?: Prisma.ActivityOrderByWithRelationInput | Prisma.ActivityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ActivityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Activities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Activities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Activities
  **/
  _count?: true | ActivityCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ActivityMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ActivityMaxAggregateInputType
}

export type GetActivityAggregateType<T extends ActivityAggregateArgs> = {
      [P in keyof T & keyof AggregateActivity]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateActivity[P]>
    : Prisma.GetScalarType<T[P], AggregateActivity[P]>
}




export type ActivityGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ActivityWhereInput
  orderBy?: Prisma.ActivityOrderByWithAggregationInput | Prisma.ActivityOrderByWithAggregationInput[]
  by: Prisma.ActivityScalarFieldEnum[] | Prisma.ActivityScalarFieldEnum
  having?: Prisma.ActivityScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ActivityCountAggregateInputType | true
  _min?: ActivityMinAggregateInputType
  _max?: ActivityMaxAggregateInputType
}

export type ActivityGroupByOutputType = {
  id: string
  companyId: string | null
  projectId: string | null
  contactId: string | null
  type: string
  date: Date
  time: string | null
  performedBy: string | null
  contactPerson: string | null
  description: string | null
  result: string | null
  nextAction: string | null
  nextFollowUp: Date | null
  notes: string | null
  createdAt: Date
  _count: ActivityCountAggregateOutputType | null
  _min: ActivityMinAggregateOutputType | null
  _max: ActivityMaxAggregateOutputType | null
}

export type GetActivityGroupByPayload<T extends ActivityGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ActivityGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ActivityGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ActivityGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ActivityGroupByOutputType[P]>
      }
    >
  >



export type ActivityWhereInput = {
  AND?: Prisma.ActivityWhereInput | Prisma.ActivityWhereInput[]
  OR?: Prisma.ActivityWhereInput[]
  NOT?: Prisma.ActivityWhereInput | Prisma.ActivityWhereInput[]
  id?: Prisma.StringFilter<"Activity"> | string
  companyId?: Prisma.StringNullableFilter<"Activity"> | string | null
  projectId?: Prisma.StringNullableFilter<"Activity"> | string | null
  contactId?: Prisma.StringNullableFilter<"Activity"> | string | null
  type?: Prisma.StringFilter<"Activity"> | string
  date?: Prisma.DateTimeFilter<"Activity"> | Date | string
  time?: Prisma.StringNullableFilter<"Activity"> | string | null
  performedBy?: Prisma.StringNullableFilter<"Activity"> | string | null
  contactPerson?: Prisma.StringNullableFilter<"Activity"> | string | null
  description?: Prisma.StringNullableFilter<"Activity"> | string | null
  result?: Prisma.StringNullableFilter<"Activity"> | string | null
  nextAction?: Prisma.StringNullableFilter<"Activity"> | string | null
  nextFollowUp?: Prisma.DateTimeNullableFilter<"Activity"> | Date | string | null
  notes?: Prisma.StringNullableFilter<"Activity"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Activity"> | Date | string
  company?: Prisma.XOR<Prisma.CompanyNullableScalarRelationFilter, Prisma.CompanyWhereInput> | null
  project?: Prisma.XOR<Prisma.ProjectNullableScalarRelationFilter, Prisma.ProjectWhereInput> | null
  contact?: Prisma.XOR<Prisma.ContactNullableScalarRelationFilter, Prisma.ContactWhereInput> | null
}

export type ActivityOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrderInput | Prisma.SortOrder
  projectId?: Prisma.SortOrderInput | Prisma.SortOrder
  contactId?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  date?: Prisma.SortOrder
  time?: Prisma.SortOrderInput | Prisma.SortOrder
  performedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  contactPerson?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  result?: Prisma.SortOrderInput | Prisma.SortOrder
  nextAction?: Prisma.SortOrderInput | Prisma.SortOrder
  nextFollowUp?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  company?: Prisma.CompanyOrderByWithRelationInput
  project?: Prisma.ProjectOrderByWithRelationInput
  contact?: Prisma.ContactOrderByWithRelationInput
}

export type ActivityWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ActivityWhereInput | Prisma.ActivityWhereInput[]
  OR?: Prisma.ActivityWhereInput[]
  NOT?: Prisma.ActivityWhereInput | Prisma.ActivityWhereInput[]
  companyId?: Prisma.StringNullableFilter<"Activity"> | string | null
  projectId?: Prisma.StringNullableFilter<"Activity"> | string | null
  contactId?: Prisma.StringNullableFilter<"Activity"> | string | null
  type?: Prisma.StringFilter<"Activity"> | string
  date?: Prisma.DateTimeFilter<"Activity"> | Date | string
  time?: Prisma.StringNullableFilter<"Activity"> | string | null
  performedBy?: Prisma.StringNullableFilter<"Activity"> | string | null
  contactPerson?: Prisma.StringNullableFilter<"Activity"> | string | null
  description?: Prisma.StringNullableFilter<"Activity"> | string | null
  result?: Prisma.StringNullableFilter<"Activity"> | string | null
  nextAction?: Prisma.StringNullableFilter<"Activity"> | string | null
  nextFollowUp?: Prisma.DateTimeNullableFilter<"Activity"> | Date | string | null
  notes?: Prisma.StringNullableFilter<"Activity"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Activity"> | Date | string
  company?: Prisma.XOR<Prisma.CompanyNullableScalarRelationFilter, Prisma.CompanyWhereInput> | null
  project?: Prisma.XOR<Prisma.ProjectNullableScalarRelationFilter, Prisma.ProjectWhereInput> | null
  contact?: Prisma.XOR<Prisma.ContactNullableScalarRelationFilter, Prisma.ContactWhereInput> | null
}, "id">

export type ActivityOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrderInput | Prisma.SortOrder
  projectId?: Prisma.SortOrderInput | Prisma.SortOrder
  contactId?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  date?: Prisma.SortOrder
  time?: Prisma.SortOrderInput | Prisma.SortOrder
  performedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  contactPerson?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  result?: Prisma.SortOrderInput | Prisma.SortOrder
  nextAction?: Prisma.SortOrderInput | Prisma.SortOrder
  nextFollowUp?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ActivityCountOrderByAggregateInput
  _max?: Prisma.ActivityMaxOrderByAggregateInput
  _min?: Prisma.ActivityMinOrderByAggregateInput
}

export type ActivityScalarWhereWithAggregatesInput = {
  AND?: Prisma.ActivityScalarWhereWithAggregatesInput | Prisma.ActivityScalarWhereWithAggregatesInput[]
  OR?: Prisma.ActivityScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ActivityScalarWhereWithAggregatesInput | Prisma.ActivityScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Activity"> | string
  companyId?: Prisma.StringNullableWithAggregatesFilter<"Activity"> | string | null
  projectId?: Prisma.StringNullableWithAggregatesFilter<"Activity"> | string | null
  contactId?: Prisma.StringNullableWithAggregatesFilter<"Activity"> | string | null
  type?: Prisma.StringWithAggregatesFilter<"Activity"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"Activity"> | Date | string
  time?: Prisma.StringNullableWithAggregatesFilter<"Activity"> | string | null
  performedBy?: Prisma.StringNullableWithAggregatesFilter<"Activity"> | string | null
  contactPerson?: Prisma.StringNullableWithAggregatesFilter<"Activity"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"Activity"> | string | null
  result?: Prisma.StringNullableWithAggregatesFilter<"Activity"> | string | null
  nextAction?: Prisma.StringNullableWithAggregatesFilter<"Activity"> | string | null
  nextFollowUp?: Prisma.DateTimeNullableWithAggregatesFilter<"Activity"> | Date | string | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"Activity"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Activity"> | Date | string
}

export type ActivityCreateInput = {
  id?: string
  type: string
  date?: Date | string
  time?: string | null
  performedBy?: string | null
  contactPerson?: string | null
  description?: string | null
  result?: string | null
  nextAction?: string | null
  nextFollowUp?: Date | string | null
  notes?: string | null
  createdAt?: Date | string
  company?: Prisma.CompanyCreateNestedOneWithoutActivitiesInput
  project?: Prisma.ProjectCreateNestedOneWithoutActivitiesInput
  contact?: Prisma.ContactCreateNestedOneWithoutActivitiesInput
}

export type ActivityUncheckedCreateInput = {
  id?: string
  companyId?: string | null
  projectId?: string | null
  contactId?: string | null
  type: string
  date?: Date | string
  time?: string | null
  performedBy?: string | null
  contactPerson?: string | null
  description?: string | null
  result?: string | null
  nextAction?: string | null
  nextFollowUp?: Date | string | null
  notes?: string | null
  createdAt?: Date | string
}

export type ActivityUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  performedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextFollowUp?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  company?: Prisma.CompanyUpdateOneWithoutActivitiesNestedInput
  project?: Prisma.ProjectUpdateOneWithoutActivitiesNestedInput
  contact?: Prisma.ContactUpdateOneWithoutActivitiesNestedInput
}

export type ActivityUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  companyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  performedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextFollowUp?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActivityCreateManyInput = {
  id?: string
  companyId?: string | null
  projectId?: string | null
  contactId?: string | null
  type: string
  date?: Date | string
  time?: string | null
  performedBy?: string | null
  contactPerson?: string | null
  description?: string | null
  result?: string | null
  nextAction?: string | null
  nextFollowUp?: Date | string | null
  notes?: string | null
  createdAt?: Date | string
}

export type ActivityUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  performedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextFollowUp?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActivityUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  companyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  performedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextFollowUp?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActivityListRelationFilter = {
  every?: Prisma.ActivityWhereInput
  some?: Prisma.ActivityWhereInput
  none?: Prisma.ActivityWhereInput
}

export type ActivityOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ActivityCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  date?: Prisma.SortOrder
  time?: Prisma.SortOrder
  performedBy?: Prisma.SortOrder
  contactPerson?: Prisma.SortOrder
  description?: Prisma.SortOrder
  result?: Prisma.SortOrder
  nextAction?: Prisma.SortOrder
  nextFollowUp?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ActivityMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  date?: Prisma.SortOrder
  time?: Prisma.SortOrder
  performedBy?: Prisma.SortOrder
  contactPerson?: Prisma.SortOrder
  description?: Prisma.SortOrder
  result?: Prisma.SortOrder
  nextAction?: Prisma.SortOrder
  nextFollowUp?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ActivityMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  date?: Prisma.SortOrder
  time?: Prisma.SortOrder
  performedBy?: Prisma.SortOrder
  contactPerson?: Prisma.SortOrder
  description?: Prisma.SortOrder
  result?: Prisma.SortOrder
  nextAction?: Prisma.SortOrder
  nextFollowUp?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ActivityCreateNestedManyWithoutCompanyInput = {
  create?: Prisma.XOR<Prisma.ActivityCreateWithoutCompanyInput, Prisma.ActivityUncheckedCreateWithoutCompanyInput> | Prisma.ActivityCreateWithoutCompanyInput[] | Prisma.ActivityUncheckedCreateWithoutCompanyInput[]
  connectOrCreate?: Prisma.ActivityCreateOrConnectWithoutCompanyInput | Prisma.ActivityCreateOrConnectWithoutCompanyInput[]
  createMany?: Prisma.ActivityCreateManyCompanyInputEnvelope
  connect?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
}

export type ActivityUncheckedCreateNestedManyWithoutCompanyInput = {
  create?: Prisma.XOR<Prisma.ActivityCreateWithoutCompanyInput, Prisma.ActivityUncheckedCreateWithoutCompanyInput> | Prisma.ActivityCreateWithoutCompanyInput[] | Prisma.ActivityUncheckedCreateWithoutCompanyInput[]
  connectOrCreate?: Prisma.ActivityCreateOrConnectWithoutCompanyInput | Prisma.ActivityCreateOrConnectWithoutCompanyInput[]
  createMany?: Prisma.ActivityCreateManyCompanyInputEnvelope
  connect?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
}

export type ActivityUpdateManyWithoutCompanyNestedInput = {
  create?: Prisma.XOR<Prisma.ActivityCreateWithoutCompanyInput, Prisma.ActivityUncheckedCreateWithoutCompanyInput> | Prisma.ActivityCreateWithoutCompanyInput[] | Prisma.ActivityUncheckedCreateWithoutCompanyInput[]
  connectOrCreate?: Prisma.ActivityCreateOrConnectWithoutCompanyInput | Prisma.ActivityCreateOrConnectWithoutCompanyInput[]
  upsert?: Prisma.ActivityUpsertWithWhereUniqueWithoutCompanyInput | Prisma.ActivityUpsertWithWhereUniqueWithoutCompanyInput[]
  createMany?: Prisma.ActivityCreateManyCompanyInputEnvelope
  set?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  disconnect?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  delete?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  connect?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  update?: Prisma.ActivityUpdateWithWhereUniqueWithoutCompanyInput | Prisma.ActivityUpdateWithWhereUniqueWithoutCompanyInput[]
  updateMany?: Prisma.ActivityUpdateManyWithWhereWithoutCompanyInput | Prisma.ActivityUpdateManyWithWhereWithoutCompanyInput[]
  deleteMany?: Prisma.ActivityScalarWhereInput | Prisma.ActivityScalarWhereInput[]
}

export type ActivityUncheckedUpdateManyWithoutCompanyNestedInput = {
  create?: Prisma.XOR<Prisma.ActivityCreateWithoutCompanyInput, Prisma.ActivityUncheckedCreateWithoutCompanyInput> | Prisma.ActivityCreateWithoutCompanyInput[] | Prisma.ActivityUncheckedCreateWithoutCompanyInput[]
  connectOrCreate?: Prisma.ActivityCreateOrConnectWithoutCompanyInput | Prisma.ActivityCreateOrConnectWithoutCompanyInput[]
  upsert?: Prisma.ActivityUpsertWithWhereUniqueWithoutCompanyInput | Prisma.ActivityUpsertWithWhereUniqueWithoutCompanyInput[]
  createMany?: Prisma.ActivityCreateManyCompanyInputEnvelope
  set?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  disconnect?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  delete?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  connect?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  update?: Prisma.ActivityUpdateWithWhereUniqueWithoutCompanyInput | Prisma.ActivityUpdateWithWhereUniqueWithoutCompanyInput[]
  updateMany?: Prisma.ActivityUpdateManyWithWhereWithoutCompanyInput | Prisma.ActivityUpdateManyWithWhereWithoutCompanyInput[]
  deleteMany?: Prisma.ActivityScalarWhereInput | Prisma.ActivityScalarWhereInput[]
}

export type ActivityCreateNestedManyWithoutContactInput = {
  create?: Prisma.XOR<Prisma.ActivityCreateWithoutContactInput, Prisma.ActivityUncheckedCreateWithoutContactInput> | Prisma.ActivityCreateWithoutContactInput[] | Prisma.ActivityUncheckedCreateWithoutContactInput[]
  connectOrCreate?: Prisma.ActivityCreateOrConnectWithoutContactInput | Prisma.ActivityCreateOrConnectWithoutContactInput[]
  createMany?: Prisma.ActivityCreateManyContactInputEnvelope
  connect?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
}

export type ActivityUncheckedCreateNestedManyWithoutContactInput = {
  create?: Prisma.XOR<Prisma.ActivityCreateWithoutContactInput, Prisma.ActivityUncheckedCreateWithoutContactInput> | Prisma.ActivityCreateWithoutContactInput[] | Prisma.ActivityUncheckedCreateWithoutContactInput[]
  connectOrCreate?: Prisma.ActivityCreateOrConnectWithoutContactInput | Prisma.ActivityCreateOrConnectWithoutContactInput[]
  createMany?: Prisma.ActivityCreateManyContactInputEnvelope
  connect?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
}

export type ActivityUpdateManyWithoutContactNestedInput = {
  create?: Prisma.XOR<Prisma.ActivityCreateWithoutContactInput, Prisma.ActivityUncheckedCreateWithoutContactInput> | Prisma.ActivityCreateWithoutContactInput[] | Prisma.ActivityUncheckedCreateWithoutContactInput[]
  connectOrCreate?: Prisma.ActivityCreateOrConnectWithoutContactInput | Prisma.ActivityCreateOrConnectWithoutContactInput[]
  upsert?: Prisma.ActivityUpsertWithWhereUniqueWithoutContactInput | Prisma.ActivityUpsertWithWhereUniqueWithoutContactInput[]
  createMany?: Prisma.ActivityCreateManyContactInputEnvelope
  set?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  disconnect?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  delete?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  connect?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  update?: Prisma.ActivityUpdateWithWhereUniqueWithoutContactInput | Prisma.ActivityUpdateWithWhereUniqueWithoutContactInput[]
  updateMany?: Prisma.ActivityUpdateManyWithWhereWithoutContactInput | Prisma.ActivityUpdateManyWithWhereWithoutContactInput[]
  deleteMany?: Prisma.ActivityScalarWhereInput | Prisma.ActivityScalarWhereInput[]
}

export type ActivityUncheckedUpdateManyWithoutContactNestedInput = {
  create?: Prisma.XOR<Prisma.ActivityCreateWithoutContactInput, Prisma.ActivityUncheckedCreateWithoutContactInput> | Prisma.ActivityCreateWithoutContactInput[] | Prisma.ActivityUncheckedCreateWithoutContactInput[]
  connectOrCreate?: Prisma.ActivityCreateOrConnectWithoutContactInput | Prisma.ActivityCreateOrConnectWithoutContactInput[]
  upsert?: Prisma.ActivityUpsertWithWhereUniqueWithoutContactInput | Prisma.ActivityUpsertWithWhereUniqueWithoutContactInput[]
  createMany?: Prisma.ActivityCreateManyContactInputEnvelope
  set?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  disconnect?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  delete?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  connect?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  update?: Prisma.ActivityUpdateWithWhereUniqueWithoutContactInput | Prisma.ActivityUpdateWithWhereUniqueWithoutContactInput[]
  updateMany?: Prisma.ActivityUpdateManyWithWhereWithoutContactInput | Prisma.ActivityUpdateManyWithWhereWithoutContactInput[]
  deleteMany?: Prisma.ActivityScalarWhereInput | Prisma.ActivityScalarWhereInput[]
}

export type ActivityCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.ActivityCreateWithoutProjectInput, Prisma.ActivityUncheckedCreateWithoutProjectInput> | Prisma.ActivityCreateWithoutProjectInput[] | Prisma.ActivityUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ActivityCreateOrConnectWithoutProjectInput | Prisma.ActivityCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.ActivityCreateManyProjectInputEnvelope
  connect?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
}

export type ActivityUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.ActivityCreateWithoutProjectInput, Prisma.ActivityUncheckedCreateWithoutProjectInput> | Prisma.ActivityCreateWithoutProjectInput[] | Prisma.ActivityUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ActivityCreateOrConnectWithoutProjectInput | Prisma.ActivityCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.ActivityCreateManyProjectInputEnvelope
  connect?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
}

export type ActivityUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.ActivityCreateWithoutProjectInput, Prisma.ActivityUncheckedCreateWithoutProjectInput> | Prisma.ActivityCreateWithoutProjectInput[] | Prisma.ActivityUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ActivityCreateOrConnectWithoutProjectInput | Prisma.ActivityCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.ActivityUpsertWithWhereUniqueWithoutProjectInput | Prisma.ActivityUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.ActivityCreateManyProjectInputEnvelope
  set?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  disconnect?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  delete?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  connect?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  update?: Prisma.ActivityUpdateWithWhereUniqueWithoutProjectInput | Prisma.ActivityUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.ActivityUpdateManyWithWhereWithoutProjectInput | Prisma.ActivityUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.ActivityScalarWhereInput | Prisma.ActivityScalarWhereInput[]
}

export type ActivityUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.ActivityCreateWithoutProjectInput, Prisma.ActivityUncheckedCreateWithoutProjectInput> | Prisma.ActivityCreateWithoutProjectInput[] | Prisma.ActivityUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ActivityCreateOrConnectWithoutProjectInput | Prisma.ActivityCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.ActivityUpsertWithWhereUniqueWithoutProjectInput | Prisma.ActivityUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.ActivityCreateManyProjectInputEnvelope
  set?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  disconnect?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  delete?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  connect?: Prisma.ActivityWhereUniqueInput | Prisma.ActivityWhereUniqueInput[]
  update?: Prisma.ActivityUpdateWithWhereUniqueWithoutProjectInput | Prisma.ActivityUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.ActivityUpdateManyWithWhereWithoutProjectInput | Prisma.ActivityUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.ActivityScalarWhereInput | Prisma.ActivityScalarWhereInput[]
}

export type ActivityCreateWithoutCompanyInput = {
  id?: string
  type: string
  date?: Date | string
  time?: string | null
  performedBy?: string | null
  contactPerson?: string | null
  description?: string | null
  result?: string | null
  nextAction?: string | null
  nextFollowUp?: Date | string | null
  notes?: string | null
  createdAt?: Date | string
  project?: Prisma.ProjectCreateNestedOneWithoutActivitiesInput
  contact?: Prisma.ContactCreateNestedOneWithoutActivitiesInput
}

export type ActivityUncheckedCreateWithoutCompanyInput = {
  id?: string
  projectId?: string | null
  contactId?: string | null
  type: string
  date?: Date | string
  time?: string | null
  performedBy?: string | null
  contactPerson?: string | null
  description?: string | null
  result?: string | null
  nextAction?: string | null
  nextFollowUp?: Date | string | null
  notes?: string | null
  createdAt?: Date | string
}

export type ActivityCreateOrConnectWithoutCompanyInput = {
  where: Prisma.ActivityWhereUniqueInput
  create: Prisma.XOR<Prisma.ActivityCreateWithoutCompanyInput, Prisma.ActivityUncheckedCreateWithoutCompanyInput>
}

export type ActivityCreateManyCompanyInputEnvelope = {
  data: Prisma.ActivityCreateManyCompanyInput | Prisma.ActivityCreateManyCompanyInput[]
  skipDuplicates?: boolean
}

export type ActivityUpsertWithWhereUniqueWithoutCompanyInput = {
  where: Prisma.ActivityWhereUniqueInput
  update: Prisma.XOR<Prisma.ActivityUpdateWithoutCompanyInput, Prisma.ActivityUncheckedUpdateWithoutCompanyInput>
  create: Prisma.XOR<Prisma.ActivityCreateWithoutCompanyInput, Prisma.ActivityUncheckedCreateWithoutCompanyInput>
}

export type ActivityUpdateWithWhereUniqueWithoutCompanyInput = {
  where: Prisma.ActivityWhereUniqueInput
  data: Prisma.XOR<Prisma.ActivityUpdateWithoutCompanyInput, Prisma.ActivityUncheckedUpdateWithoutCompanyInput>
}

export type ActivityUpdateManyWithWhereWithoutCompanyInput = {
  where: Prisma.ActivityScalarWhereInput
  data: Prisma.XOR<Prisma.ActivityUpdateManyMutationInput, Prisma.ActivityUncheckedUpdateManyWithoutCompanyInput>
}

export type ActivityScalarWhereInput = {
  AND?: Prisma.ActivityScalarWhereInput | Prisma.ActivityScalarWhereInput[]
  OR?: Prisma.ActivityScalarWhereInput[]
  NOT?: Prisma.ActivityScalarWhereInput | Prisma.ActivityScalarWhereInput[]
  id?: Prisma.StringFilter<"Activity"> | string
  companyId?: Prisma.StringNullableFilter<"Activity"> | string | null
  projectId?: Prisma.StringNullableFilter<"Activity"> | string | null
  contactId?: Prisma.StringNullableFilter<"Activity"> | string | null
  type?: Prisma.StringFilter<"Activity"> | string
  date?: Prisma.DateTimeFilter<"Activity"> | Date | string
  time?: Prisma.StringNullableFilter<"Activity"> | string | null
  performedBy?: Prisma.StringNullableFilter<"Activity"> | string | null
  contactPerson?: Prisma.StringNullableFilter<"Activity"> | string | null
  description?: Prisma.StringNullableFilter<"Activity"> | string | null
  result?: Prisma.StringNullableFilter<"Activity"> | string | null
  nextAction?: Prisma.StringNullableFilter<"Activity"> | string | null
  nextFollowUp?: Prisma.DateTimeNullableFilter<"Activity"> | Date | string | null
  notes?: Prisma.StringNullableFilter<"Activity"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Activity"> | Date | string
}

export type ActivityCreateWithoutContactInput = {
  id?: string
  type: string
  date?: Date | string
  time?: string | null
  performedBy?: string | null
  contactPerson?: string | null
  description?: string | null
  result?: string | null
  nextAction?: string | null
  nextFollowUp?: Date | string | null
  notes?: string | null
  createdAt?: Date | string
  company?: Prisma.CompanyCreateNestedOneWithoutActivitiesInput
  project?: Prisma.ProjectCreateNestedOneWithoutActivitiesInput
}

export type ActivityUncheckedCreateWithoutContactInput = {
  id?: string
  companyId?: string | null
  projectId?: string | null
  type: string
  date?: Date | string
  time?: string | null
  performedBy?: string | null
  contactPerson?: string | null
  description?: string | null
  result?: string | null
  nextAction?: string | null
  nextFollowUp?: Date | string | null
  notes?: string | null
  createdAt?: Date | string
}

export type ActivityCreateOrConnectWithoutContactInput = {
  where: Prisma.ActivityWhereUniqueInput
  create: Prisma.XOR<Prisma.ActivityCreateWithoutContactInput, Prisma.ActivityUncheckedCreateWithoutContactInput>
}

export type ActivityCreateManyContactInputEnvelope = {
  data: Prisma.ActivityCreateManyContactInput | Prisma.ActivityCreateManyContactInput[]
  skipDuplicates?: boolean
}

export type ActivityUpsertWithWhereUniqueWithoutContactInput = {
  where: Prisma.ActivityWhereUniqueInput
  update: Prisma.XOR<Prisma.ActivityUpdateWithoutContactInput, Prisma.ActivityUncheckedUpdateWithoutContactInput>
  create: Prisma.XOR<Prisma.ActivityCreateWithoutContactInput, Prisma.ActivityUncheckedCreateWithoutContactInput>
}

export type ActivityUpdateWithWhereUniqueWithoutContactInput = {
  where: Prisma.ActivityWhereUniqueInput
  data: Prisma.XOR<Prisma.ActivityUpdateWithoutContactInput, Prisma.ActivityUncheckedUpdateWithoutContactInput>
}

export type ActivityUpdateManyWithWhereWithoutContactInput = {
  where: Prisma.ActivityScalarWhereInput
  data: Prisma.XOR<Prisma.ActivityUpdateManyMutationInput, Prisma.ActivityUncheckedUpdateManyWithoutContactInput>
}

export type ActivityCreateWithoutProjectInput = {
  id?: string
  type: string
  date?: Date | string
  time?: string | null
  performedBy?: string | null
  contactPerson?: string | null
  description?: string | null
  result?: string | null
  nextAction?: string | null
  nextFollowUp?: Date | string | null
  notes?: string | null
  createdAt?: Date | string
  company?: Prisma.CompanyCreateNestedOneWithoutActivitiesInput
  contact?: Prisma.ContactCreateNestedOneWithoutActivitiesInput
}

export type ActivityUncheckedCreateWithoutProjectInput = {
  id?: string
  companyId?: string | null
  contactId?: string | null
  type: string
  date?: Date | string
  time?: string | null
  performedBy?: string | null
  contactPerson?: string | null
  description?: string | null
  result?: string | null
  nextAction?: string | null
  nextFollowUp?: Date | string | null
  notes?: string | null
  createdAt?: Date | string
}

export type ActivityCreateOrConnectWithoutProjectInput = {
  where: Prisma.ActivityWhereUniqueInput
  create: Prisma.XOR<Prisma.ActivityCreateWithoutProjectInput, Prisma.ActivityUncheckedCreateWithoutProjectInput>
}

export type ActivityCreateManyProjectInputEnvelope = {
  data: Prisma.ActivityCreateManyProjectInput | Prisma.ActivityCreateManyProjectInput[]
  skipDuplicates?: boolean
}

export type ActivityUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.ActivityWhereUniqueInput
  update: Prisma.XOR<Prisma.ActivityUpdateWithoutProjectInput, Prisma.ActivityUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.ActivityCreateWithoutProjectInput, Prisma.ActivityUncheckedCreateWithoutProjectInput>
}

export type ActivityUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.ActivityWhereUniqueInput
  data: Prisma.XOR<Prisma.ActivityUpdateWithoutProjectInput, Prisma.ActivityUncheckedUpdateWithoutProjectInput>
}

export type ActivityUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.ActivityScalarWhereInput
  data: Prisma.XOR<Prisma.ActivityUpdateManyMutationInput, Prisma.ActivityUncheckedUpdateManyWithoutProjectInput>
}

export type ActivityCreateManyCompanyInput = {
  id?: string
  projectId?: string | null
  contactId?: string | null
  type: string
  date?: Date | string
  time?: string | null
  performedBy?: string | null
  contactPerson?: string | null
  description?: string | null
  result?: string | null
  nextAction?: string | null
  nextFollowUp?: Date | string | null
  notes?: string | null
  createdAt?: Date | string
}

export type ActivityUpdateWithoutCompanyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  performedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextFollowUp?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneWithoutActivitiesNestedInput
  contact?: Prisma.ContactUpdateOneWithoutActivitiesNestedInput
}

export type ActivityUncheckedUpdateWithoutCompanyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  performedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextFollowUp?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActivityUncheckedUpdateManyWithoutCompanyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  performedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextFollowUp?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActivityCreateManyContactInput = {
  id?: string
  companyId?: string | null
  projectId?: string | null
  type: string
  date?: Date | string
  time?: string | null
  performedBy?: string | null
  contactPerson?: string | null
  description?: string | null
  result?: string | null
  nextAction?: string | null
  nextFollowUp?: Date | string | null
  notes?: string | null
  createdAt?: Date | string
}

export type ActivityUpdateWithoutContactInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  performedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextFollowUp?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  company?: Prisma.CompanyUpdateOneWithoutActivitiesNestedInput
  project?: Prisma.ProjectUpdateOneWithoutActivitiesNestedInput
}

export type ActivityUncheckedUpdateWithoutContactInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  companyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  performedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextFollowUp?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActivityUncheckedUpdateManyWithoutContactInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  companyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  performedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextFollowUp?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActivityCreateManyProjectInput = {
  id?: string
  companyId?: string | null
  contactId?: string | null
  type: string
  date?: Date | string
  time?: string | null
  performedBy?: string | null
  contactPerson?: string | null
  description?: string | null
  result?: string | null
  nextAction?: string | null
  nextFollowUp?: Date | string | null
  notes?: string | null
  createdAt?: Date | string
}

export type ActivityUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  performedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextFollowUp?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  company?: Prisma.CompanyUpdateOneWithoutActivitiesNestedInput
  contact?: Prisma.ContactUpdateOneWithoutActivitiesNestedInput
}

export type ActivityUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  companyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  performedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextFollowUp?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActivityUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  companyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  performedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextFollowUp?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ActivitySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  companyId?: boolean
  projectId?: boolean
  contactId?: boolean
  type?: boolean
  date?: boolean
  time?: boolean
  performedBy?: boolean
  contactPerson?: boolean
  description?: boolean
  result?: boolean
  nextAction?: boolean
  nextFollowUp?: boolean
  notes?: boolean
  createdAt?: boolean
  company?: boolean | Prisma.Activity$companyArgs<ExtArgs>
  project?: boolean | Prisma.Activity$projectArgs<ExtArgs>
  contact?: boolean | Prisma.Activity$contactArgs<ExtArgs>
}, ExtArgs["result"]["activity"]>

export type ActivitySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  companyId?: boolean
  projectId?: boolean
  contactId?: boolean
  type?: boolean
  date?: boolean
  time?: boolean
  performedBy?: boolean
  contactPerson?: boolean
  description?: boolean
  result?: boolean
  nextAction?: boolean
  nextFollowUp?: boolean
  notes?: boolean
  createdAt?: boolean
  company?: boolean | Prisma.Activity$companyArgs<ExtArgs>
  project?: boolean | Prisma.Activity$projectArgs<ExtArgs>
  contact?: boolean | Prisma.Activity$contactArgs<ExtArgs>
}, ExtArgs["result"]["activity"]>

export type ActivitySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  companyId?: boolean
  projectId?: boolean
  contactId?: boolean
  type?: boolean
  date?: boolean
  time?: boolean
  performedBy?: boolean
  contactPerson?: boolean
  description?: boolean
  result?: boolean
  nextAction?: boolean
  nextFollowUp?: boolean
  notes?: boolean
  createdAt?: boolean
  company?: boolean | Prisma.Activity$companyArgs<ExtArgs>
  project?: boolean | Prisma.Activity$projectArgs<ExtArgs>
  contact?: boolean | Prisma.Activity$contactArgs<ExtArgs>
}, ExtArgs["result"]["activity"]>

export type ActivitySelectScalar = {
  id?: boolean
  companyId?: boolean
  projectId?: boolean
  contactId?: boolean
  type?: boolean
  date?: boolean
  time?: boolean
  performedBy?: boolean
  contactPerson?: boolean
  description?: boolean
  result?: boolean
  nextAction?: boolean
  nextFollowUp?: boolean
  notes?: boolean
  createdAt?: boolean
}

export type ActivityOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "companyId" | "projectId" | "contactId" | "type" | "date" | "time" | "performedBy" | "contactPerson" | "description" | "result" | "nextAction" | "nextFollowUp" | "notes" | "createdAt", ExtArgs["result"]["activity"]>
export type ActivityInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  company?: boolean | Prisma.Activity$companyArgs<ExtArgs>
  project?: boolean | Prisma.Activity$projectArgs<ExtArgs>
  contact?: boolean | Prisma.Activity$contactArgs<ExtArgs>
}
export type ActivityIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  company?: boolean | Prisma.Activity$companyArgs<ExtArgs>
  project?: boolean | Prisma.Activity$projectArgs<ExtArgs>
  contact?: boolean | Prisma.Activity$contactArgs<ExtArgs>
}
export type ActivityIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  company?: boolean | Prisma.Activity$companyArgs<ExtArgs>
  project?: boolean | Prisma.Activity$projectArgs<ExtArgs>
  contact?: boolean | Prisma.Activity$contactArgs<ExtArgs>
}

export type $ActivityPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Activity"
  objects: {
    company: Prisma.$CompanyPayload<ExtArgs> | null
    project: Prisma.$ProjectPayload<ExtArgs> | null
    contact: Prisma.$ContactPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    companyId: string | null
    projectId: string | null
    contactId: string | null
    type: string
    date: Date
    time: string | null
    performedBy: string | null
    contactPerson: string | null
    description: string | null
    result: string | null
    nextAction: string | null
    nextFollowUp: Date | null
    notes: string | null
    createdAt: Date
  }, ExtArgs["result"]["activity"]>
  composites: {}
}

export type ActivityGetPayload<S extends boolean | null | undefined | ActivityDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ActivityPayload, S>

export type ActivityCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ActivityFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ActivityCountAggregateInputType | true
  }

export interface ActivityDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Activity'], meta: { name: 'Activity' } }
  /**
   * Find zero or one Activity that matches the filter.
   * @param {ActivityFindUniqueArgs} args - Arguments to find a Activity
   * @example
   * // Get one Activity
   * const activity = await prisma.activity.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ActivityFindUniqueArgs>(args: Prisma.SelectSubset<T, ActivityFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ActivityClient<runtime.Types.Result.GetResult<Prisma.$ActivityPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Activity that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ActivityFindUniqueOrThrowArgs} args - Arguments to find a Activity
   * @example
   * // Get one Activity
   * const activity = await prisma.activity.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ActivityFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ActivityFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ActivityClient<runtime.Types.Result.GetResult<Prisma.$ActivityPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Activity that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActivityFindFirstArgs} args - Arguments to find a Activity
   * @example
   * // Get one Activity
   * const activity = await prisma.activity.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ActivityFindFirstArgs>(args?: Prisma.SelectSubset<T, ActivityFindFirstArgs<ExtArgs>>): Prisma.Prisma__ActivityClient<runtime.Types.Result.GetResult<Prisma.$ActivityPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Activity that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActivityFindFirstOrThrowArgs} args - Arguments to find a Activity
   * @example
   * // Get one Activity
   * const activity = await prisma.activity.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ActivityFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ActivityFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ActivityClient<runtime.Types.Result.GetResult<Prisma.$ActivityPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Activities that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActivityFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Activities
   * const activities = await prisma.activity.findMany()
   * 
   * // Get first 10 Activities
   * const activities = await prisma.activity.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const activityWithIdOnly = await prisma.activity.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ActivityFindManyArgs>(args?: Prisma.SelectSubset<T, ActivityFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActivityPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Activity.
   * @param {ActivityCreateArgs} args - Arguments to create a Activity.
   * @example
   * // Create one Activity
   * const Activity = await prisma.activity.create({
   *   data: {
   *     // ... data to create a Activity
   *   }
   * })
   * 
   */
  create<T extends ActivityCreateArgs>(args: Prisma.SelectSubset<T, ActivityCreateArgs<ExtArgs>>): Prisma.Prisma__ActivityClient<runtime.Types.Result.GetResult<Prisma.$ActivityPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Activities.
   * @param {ActivityCreateManyArgs} args - Arguments to create many Activities.
   * @example
   * // Create many Activities
   * const activity = await prisma.activity.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ActivityCreateManyArgs>(args?: Prisma.SelectSubset<T, ActivityCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Activities and returns the data saved in the database.
   * @param {ActivityCreateManyAndReturnArgs} args - Arguments to create many Activities.
   * @example
   * // Create many Activities
   * const activity = await prisma.activity.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Activities and only return the `id`
   * const activityWithIdOnly = await prisma.activity.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ActivityCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ActivityCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActivityPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Activity.
   * @param {ActivityDeleteArgs} args - Arguments to delete one Activity.
   * @example
   * // Delete one Activity
   * const Activity = await prisma.activity.delete({
   *   where: {
   *     // ... filter to delete one Activity
   *   }
   * })
   * 
   */
  delete<T extends ActivityDeleteArgs>(args: Prisma.SelectSubset<T, ActivityDeleteArgs<ExtArgs>>): Prisma.Prisma__ActivityClient<runtime.Types.Result.GetResult<Prisma.$ActivityPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Activity.
   * @param {ActivityUpdateArgs} args - Arguments to update one Activity.
   * @example
   * // Update one Activity
   * const activity = await prisma.activity.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ActivityUpdateArgs>(args: Prisma.SelectSubset<T, ActivityUpdateArgs<ExtArgs>>): Prisma.Prisma__ActivityClient<runtime.Types.Result.GetResult<Prisma.$ActivityPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Activities.
   * @param {ActivityDeleteManyArgs} args - Arguments to filter Activities to delete.
   * @example
   * // Delete a few Activities
   * const { count } = await prisma.activity.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ActivityDeleteManyArgs>(args?: Prisma.SelectSubset<T, ActivityDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Activities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActivityUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Activities
   * const activity = await prisma.activity.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ActivityUpdateManyArgs>(args: Prisma.SelectSubset<T, ActivityUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Activities and returns the data updated in the database.
   * @param {ActivityUpdateManyAndReturnArgs} args - Arguments to update many Activities.
   * @example
   * // Update many Activities
   * const activity = await prisma.activity.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Activities and only return the `id`
   * const activityWithIdOnly = await prisma.activity.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ActivityUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ActivityUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActivityPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Activity.
   * @param {ActivityUpsertArgs} args - Arguments to update or create a Activity.
   * @example
   * // Update or create a Activity
   * const activity = await prisma.activity.upsert({
   *   create: {
   *     // ... data to create a Activity
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Activity we want to update
   *   }
   * })
   */
  upsert<T extends ActivityUpsertArgs>(args: Prisma.SelectSubset<T, ActivityUpsertArgs<ExtArgs>>): Prisma.Prisma__ActivityClient<runtime.Types.Result.GetResult<Prisma.$ActivityPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Activities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActivityCountArgs} args - Arguments to filter Activities to count.
   * @example
   * // Count the number of Activities
   * const count = await prisma.activity.count({
   *   where: {
   *     // ... the filter for the Activities we want to count
   *   }
   * })
  **/
  count<T extends ActivityCountArgs>(
    args?: Prisma.Subset<T, ActivityCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ActivityCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Activity.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActivityAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ActivityAggregateArgs>(args: Prisma.Subset<T, ActivityAggregateArgs>): Prisma.PrismaPromise<GetActivityAggregateType<T>>

  /**
   * Group by Activity.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActivityGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ActivityGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ActivityGroupByArgs['orderBy'] }
      : { orderBy?: ActivityGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ActivityGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetActivityGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Activity model
 */
readonly fields: ActivityFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Activity.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ActivityClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  company<T extends Prisma.Activity$companyArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Activity$companyArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  project<T extends Prisma.Activity$projectArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Activity$projectArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  contact<T extends Prisma.Activity$contactArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Activity$contactArgs<ExtArgs>>): Prisma.Prisma__ContactClient<runtime.Types.Result.GetResult<Prisma.$ContactPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Activity model
 */
export interface ActivityFieldRefs {
  readonly id: Prisma.FieldRef<"Activity", 'String'>
  readonly companyId: Prisma.FieldRef<"Activity", 'String'>
  readonly projectId: Prisma.FieldRef<"Activity", 'String'>
  readonly contactId: Prisma.FieldRef<"Activity", 'String'>
  readonly type: Prisma.FieldRef<"Activity", 'String'>
  readonly date: Prisma.FieldRef<"Activity", 'DateTime'>
  readonly time: Prisma.FieldRef<"Activity", 'String'>
  readonly performedBy: Prisma.FieldRef<"Activity", 'String'>
  readonly contactPerson: Prisma.FieldRef<"Activity", 'String'>
  readonly description: Prisma.FieldRef<"Activity", 'String'>
  readonly result: Prisma.FieldRef<"Activity", 'String'>
  readonly nextAction: Prisma.FieldRef<"Activity", 'String'>
  readonly nextFollowUp: Prisma.FieldRef<"Activity", 'DateTime'>
  readonly notes: Prisma.FieldRef<"Activity", 'String'>
  readonly createdAt: Prisma.FieldRef<"Activity", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Activity findUnique
 */
export type ActivityFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Activity
   */
  select?: Prisma.ActivitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Activity
   */
  omit?: Prisma.ActivityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityInclude<ExtArgs> | null
  /**
   * Filter, which Activity to fetch.
   */
  where: Prisma.ActivityWhereUniqueInput
}

/**
 * Activity findUniqueOrThrow
 */
export type ActivityFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Activity
   */
  select?: Prisma.ActivitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Activity
   */
  omit?: Prisma.ActivityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityInclude<ExtArgs> | null
  /**
   * Filter, which Activity to fetch.
   */
  where: Prisma.ActivityWhereUniqueInput
}

/**
 * Activity findFirst
 */
export type ActivityFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Activity
   */
  select?: Prisma.ActivitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Activity
   */
  omit?: Prisma.ActivityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityInclude<ExtArgs> | null
  /**
   * Filter, which Activity to fetch.
   */
  where?: Prisma.ActivityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Activities to fetch.
   */
  orderBy?: Prisma.ActivityOrderByWithRelationInput | Prisma.ActivityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Activities.
   */
  cursor?: Prisma.ActivityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Activities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Activities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Activities.
   */
  distinct?: Prisma.ActivityScalarFieldEnum | Prisma.ActivityScalarFieldEnum[]
}

/**
 * Activity findFirstOrThrow
 */
export type ActivityFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Activity
   */
  select?: Prisma.ActivitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Activity
   */
  omit?: Prisma.ActivityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityInclude<ExtArgs> | null
  /**
   * Filter, which Activity to fetch.
   */
  where?: Prisma.ActivityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Activities to fetch.
   */
  orderBy?: Prisma.ActivityOrderByWithRelationInput | Prisma.ActivityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Activities.
   */
  cursor?: Prisma.ActivityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Activities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Activities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Activities.
   */
  distinct?: Prisma.ActivityScalarFieldEnum | Prisma.ActivityScalarFieldEnum[]
}

/**
 * Activity findMany
 */
export type ActivityFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Activity
   */
  select?: Prisma.ActivitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Activity
   */
  omit?: Prisma.ActivityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityInclude<ExtArgs> | null
  /**
   * Filter, which Activities to fetch.
   */
  where?: Prisma.ActivityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Activities to fetch.
   */
  orderBy?: Prisma.ActivityOrderByWithRelationInput | Prisma.ActivityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Activities.
   */
  cursor?: Prisma.ActivityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Activities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Activities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Activities.
   */
  distinct?: Prisma.ActivityScalarFieldEnum | Prisma.ActivityScalarFieldEnum[]
}

/**
 * Activity create
 */
export type ActivityCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Activity
   */
  select?: Prisma.ActivitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Activity
   */
  omit?: Prisma.ActivityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityInclude<ExtArgs> | null
  /**
   * The data needed to create a Activity.
   */
  data: Prisma.XOR<Prisma.ActivityCreateInput, Prisma.ActivityUncheckedCreateInput>
}

/**
 * Activity createMany
 */
export type ActivityCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Activities.
   */
  data: Prisma.ActivityCreateManyInput | Prisma.ActivityCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Activity createManyAndReturn
 */
export type ActivityCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Activity
   */
  select?: Prisma.ActivitySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Activity
   */
  omit?: Prisma.ActivityOmit<ExtArgs> | null
  /**
   * The data used to create many Activities.
   */
  data: Prisma.ActivityCreateManyInput | Prisma.ActivityCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Activity update
 */
export type ActivityUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Activity
   */
  select?: Prisma.ActivitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Activity
   */
  omit?: Prisma.ActivityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityInclude<ExtArgs> | null
  /**
   * The data needed to update a Activity.
   */
  data: Prisma.XOR<Prisma.ActivityUpdateInput, Prisma.ActivityUncheckedUpdateInput>
  /**
   * Choose, which Activity to update.
   */
  where: Prisma.ActivityWhereUniqueInput
}

/**
 * Activity updateMany
 */
export type ActivityUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Activities.
   */
  data: Prisma.XOR<Prisma.ActivityUpdateManyMutationInput, Prisma.ActivityUncheckedUpdateManyInput>
  /**
   * Filter which Activities to update
   */
  where?: Prisma.ActivityWhereInput
  /**
   * Limit how many Activities to update.
   */
  limit?: number
}

/**
 * Activity updateManyAndReturn
 */
export type ActivityUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Activity
   */
  select?: Prisma.ActivitySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Activity
   */
  omit?: Prisma.ActivityOmit<ExtArgs> | null
  /**
   * The data used to update Activities.
   */
  data: Prisma.XOR<Prisma.ActivityUpdateManyMutationInput, Prisma.ActivityUncheckedUpdateManyInput>
  /**
   * Filter which Activities to update
   */
  where?: Prisma.ActivityWhereInput
  /**
   * Limit how many Activities to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Activity upsert
 */
export type ActivityUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Activity
   */
  select?: Prisma.ActivitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Activity
   */
  omit?: Prisma.ActivityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityInclude<ExtArgs> | null
  /**
   * The filter to search for the Activity to update in case it exists.
   */
  where: Prisma.ActivityWhereUniqueInput
  /**
   * In case the Activity found by the `where` argument doesn't exist, create a new Activity with this data.
   */
  create: Prisma.XOR<Prisma.ActivityCreateInput, Prisma.ActivityUncheckedCreateInput>
  /**
   * In case the Activity was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ActivityUpdateInput, Prisma.ActivityUncheckedUpdateInput>
}

/**
 * Activity delete
 */
export type ActivityDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Activity
   */
  select?: Prisma.ActivitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Activity
   */
  omit?: Prisma.ActivityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityInclude<ExtArgs> | null
  /**
   * Filter which Activity to delete.
   */
  where: Prisma.ActivityWhereUniqueInput
}

/**
 * Activity deleteMany
 */
export type ActivityDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Activities to delete
   */
  where?: Prisma.ActivityWhereInput
  /**
   * Limit how many Activities to delete.
   */
  limit?: number
}

/**
 * Activity.company
 */
export type Activity$companyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
  where?: Prisma.CompanyWhereInput
}

/**
 * Activity.project
 */
export type Activity$projectArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  where?: Prisma.ProjectWhereInput
}

/**
 * Activity.contact
 */
export type Activity$contactArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contact
   */
  select?: Prisma.ContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contact
   */
  omit?: Prisma.ContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactInclude<ExtArgs> | null
  where?: Prisma.ContactWhereInput
}

/**
 * Activity without action
 */
export type ActivityDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Activity
   */
  select?: Prisma.ActivitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Activity
   */
  omit?: Prisma.ActivityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityInclude<ExtArgs> | null
}
