
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `StatusDefinition` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model StatusDefinition
 * 
 */
export type StatusDefinitionModel = runtime.Types.Result.DefaultSelection<Prisma.$StatusDefinitionPayload>

export type AggregateStatusDefinition = {
  _count: StatusDefinitionCountAggregateOutputType | null
  _min: StatusDefinitionMinAggregateOutputType | null
  _max: StatusDefinitionMaxAggregateOutputType | null
}

export type StatusDefinitionMinAggregateOutputType = {
  id: string | null
  name: string | null
  type: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type StatusDefinitionMaxAggregateOutputType = {
  id: string | null
  name: string | null
  type: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type StatusDefinitionCountAggregateOutputType = {
  id: number
  name: number
  type: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type StatusDefinitionMinAggregateInputType = {
  id?: true
  name?: true
  type?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type StatusDefinitionMaxAggregateInputType = {
  id?: true
  name?: true
  type?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type StatusDefinitionCountAggregateInputType = {
  id?: true
  name?: true
  type?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type StatusDefinitionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StatusDefinition to aggregate.
   */
  where?: Prisma.StatusDefinitionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StatusDefinitions to fetch.
   */
  orderBy?: Prisma.StatusDefinitionOrderByWithRelationInput | Prisma.StatusDefinitionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StatusDefinitionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StatusDefinitions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StatusDefinitions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StatusDefinitions
  **/
  _count?: true | StatusDefinitionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StatusDefinitionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StatusDefinitionMaxAggregateInputType
}

export type GetStatusDefinitionAggregateType<T extends StatusDefinitionAggregateArgs> = {
      [P in keyof T & keyof AggregateStatusDefinition]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStatusDefinition[P]>
    : Prisma.GetScalarType<T[P], AggregateStatusDefinition[P]>
}




export type StatusDefinitionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StatusDefinitionWhereInput
  orderBy?: Prisma.StatusDefinitionOrderByWithAggregationInput | Prisma.StatusDefinitionOrderByWithAggregationInput[]
  by: Prisma.StatusDefinitionScalarFieldEnum[] | Prisma.StatusDefinitionScalarFieldEnum
  having?: Prisma.StatusDefinitionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StatusDefinitionCountAggregateInputType | true
  _min?: StatusDefinitionMinAggregateInputType
  _max?: StatusDefinitionMaxAggregateInputType
}

export type StatusDefinitionGroupByOutputType = {
  id: string
  name: string
  type: string
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  _count: StatusDefinitionCountAggregateOutputType | null
  _min: StatusDefinitionMinAggregateOutputType | null
  _max: StatusDefinitionMaxAggregateOutputType | null
}

export type GetStatusDefinitionGroupByPayload<T extends StatusDefinitionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StatusDefinitionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StatusDefinitionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StatusDefinitionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StatusDefinitionGroupByOutputType[P]>
      }
    >
  >



export type StatusDefinitionWhereInput = {
  AND?: Prisma.StatusDefinitionWhereInput | Prisma.StatusDefinitionWhereInput[]
  OR?: Prisma.StatusDefinitionWhereInput[]
  NOT?: Prisma.StatusDefinitionWhereInput | Prisma.StatusDefinitionWhereInput[]
  id?: Prisma.StringFilter<"StatusDefinition"> | string
  name?: Prisma.StringFilter<"StatusDefinition"> | string
  type?: Prisma.StringFilter<"StatusDefinition"> | string
  isActive?: Prisma.BoolFilter<"StatusDefinition"> | boolean
  createdAt?: Prisma.DateTimeFilter<"StatusDefinition"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"StatusDefinition"> | Date | string
}

export type StatusDefinitionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StatusDefinitionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name_type?: Prisma.StatusDefinitionNameTypeCompoundUniqueInput
  AND?: Prisma.StatusDefinitionWhereInput | Prisma.StatusDefinitionWhereInput[]
  OR?: Prisma.StatusDefinitionWhereInput[]
  NOT?: Prisma.StatusDefinitionWhereInput | Prisma.StatusDefinitionWhereInput[]
  name?: Prisma.StringFilter<"StatusDefinition"> | string
  type?: Prisma.StringFilter<"StatusDefinition"> | string
  isActive?: Prisma.BoolFilter<"StatusDefinition"> | boolean
  createdAt?: Prisma.DateTimeFilter<"StatusDefinition"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"StatusDefinition"> | Date | string
}, "id" | "name_type">

export type StatusDefinitionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.StatusDefinitionCountOrderByAggregateInput
  _max?: Prisma.StatusDefinitionMaxOrderByAggregateInput
  _min?: Prisma.StatusDefinitionMinOrderByAggregateInput
}

export type StatusDefinitionScalarWhereWithAggregatesInput = {
  AND?: Prisma.StatusDefinitionScalarWhereWithAggregatesInput | Prisma.StatusDefinitionScalarWhereWithAggregatesInput[]
  OR?: Prisma.StatusDefinitionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StatusDefinitionScalarWhereWithAggregatesInput | Prisma.StatusDefinitionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"StatusDefinition"> | string
  name?: Prisma.StringWithAggregatesFilter<"StatusDefinition"> | string
  type?: Prisma.StringWithAggregatesFilter<"StatusDefinition"> | string
  isActive?: Prisma.BoolWithAggregatesFilter<"StatusDefinition"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"StatusDefinition"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"StatusDefinition"> | Date | string
}

export type StatusDefinitionCreateInput = {
  id?: string
  name: string
  type: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StatusDefinitionUncheckedCreateInput = {
  id?: string
  name: string
  type: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StatusDefinitionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StatusDefinitionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StatusDefinitionCreateManyInput = {
  id?: string
  name: string
  type: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StatusDefinitionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StatusDefinitionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StatusDefinitionNameTypeCompoundUniqueInput = {
  name: string
  type: string
}

export type StatusDefinitionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StatusDefinitionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StatusDefinitionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}



export type StatusDefinitionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  type?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["statusDefinition"]>

export type StatusDefinitionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  type?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["statusDefinition"]>

export type StatusDefinitionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  type?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["statusDefinition"]>

export type StatusDefinitionSelectScalar = {
  id?: boolean
  name?: boolean
  type?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type StatusDefinitionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "type" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["statusDefinition"]>

export type $StatusDefinitionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StatusDefinition"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    type: string
    isActive: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["statusDefinition"]>
  composites: {}
}

export type StatusDefinitionGetPayload<S extends boolean | null | undefined | StatusDefinitionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StatusDefinitionPayload, S>

export type StatusDefinitionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StatusDefinitionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StatusDefinitionCountAggregateInputType | true
  }

export interface StatusDefinitionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StatusDefinition'], meta: { name: 'StatusDefinition' } }
  /**
   * Find zero or one StatusDefinition that matches the filter.
   * @param {StatusDefinitionFindUniqueArgs} args - Arguments to find a StatusDefinition
   * @example
   * // Get one StatusDefinition
   * const statusDefinition = await prisma.statusDefinition.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StatusDefinitionFindUniqueArgs>(args: Prisma.SelectSubset<T, StatusDefinitionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StatusDefinitionClient<runtime.Types.Result.GetResult<Prisma.$StatusDefinitionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StatusDefinition that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StatusDefinitionFindUniqueOrThrowArgs} args - Arguments to find a StatusDefinition
   * @example
   * // Get one StatusDefinition
   * const statusDefinition = await prisma.statusDefinition.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StatusDefinitionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StatusDefinitionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StatusDefinitionClient<runtime.Types.Result.GetResult<Prisma.$StatusDefinitionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StatusDefinition that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StatusDefinitionFindFirstArgs} args - Arguments to find a StatusDefinition
   * @example
   * // Get one StatusDefinition
   * const statusDefinition = await prisma.statusDefinition.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StatusDefinitionFindFirstArgs>(args?: Prisma.SelectSubset<T, StatusDefinitionFindFirstArgs<ExtArgs>>): Prisma.Prisma__StatusDefinitionClient<runtime.Types.Result.GetResult<Prisma.$StatusDefinitionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StatusDefinition that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StatusDefinitionFindFirstOrThrowArgs} args - Arguments to find a StatusDefinition
   * @example
   * // Get one StatusDefinition
   * const statusDefinition = await prisma.statusDefinition.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StatusDefinitionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StatusDefinitionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StatusDefinitionClient<runtime.Types.Result.GetResult<Prisma.$StatusDefinitionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StatusDefinitions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StatusDefinitionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StatusDefinitions
   * const statusDefinitions = await prisma.statusDefinition.findMany()
   * 
   * // Get first 10 StatusDefinitions
   * const statusDefinitions = await prisma.statusDefinition.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const statusDefinitionWithIdOnly = await prisma.statusDefinition.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StatusDefinitionFindManyArgs>(args?: Prisma.SelectSubset<T, StatusDefinitionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StatusDefinitionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StatusDefinition.
   * @param {StatusDefinitionCreateArgs} args - Arguments to create a StatusDefinition.
   * @example
   * // Create one StatusDefinition
   * const StatusDefinition = await prisma.statusDefinition.create({
   *   data: {
   *     // ... data to create a StatusDefinition
   *   }
   * })
   * 
   */
  create<T extends StatusDefinitionCreateArgs>(args: Prisma.SelectSubset<T, StatusDefinitionCreateArgs<ExtArgs>>): Prisma.Prisma__StatusDefinitionClient<runtime.Types.Result.GetResult<Prisma.$StatusDefinitionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StatusDefinitions.
   * @param {StatusDefinitionCreateManyArgs} args - Arguments to create many StatusDefinitions.
   * @example
   * // Create many StatusDefinitions
   * const statusDefinition = await prisma.statusDefinition.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StatusDefinitionCreateManyArgs>(args?: Prisma.SelectSubset<T, StatusDefinitionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many StatusDefinitions and returns the data saved in the database.
   * @param {StatusDefinitionCreateManyAndReturnArgs} args - Arguments to create many StatusDefinitions.
   * @example
   * // Create many StatusDefinitions
   * const statusDefinition = await prisma.statusDefinition.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many StatusDefinitions and only return the `id`
   * const statusDefinitionWithIdOnly = await prisma.statusDefinition.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StatusDefinitionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StatusDefinitionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StatusDefinitionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a StatusDefinition.
   * @param {StatusDefinitionDeleteArgs} args - Arguments to delete one StatusDefinition.
   * @example
   * // Delete one StatusDefinition
   * const StatusDefinition = await prisma.statusDefinition.delete({
   *   where: {
   *     // ... filter to delete one StatusDefinition
   *   }
   * })
   * 
   */
  delete<T extends StatusDefinitionDeleteArgs>(args: Prisma.SelectSubset<T, StatusDefinitionDeleteArgs<ExtArgs>>): Prisma.Prisma__StatusDefinitionClient<runtime.Types.Result.GetResult<Prisma.$StatusDefinitionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StatusDefinition.
   * @param {StatusDefinitionUpdateArgs} args - Arguments to update one StatusDefinition.
   * @example
   * // Update one StatusDefinition
   * const statusDefinition = await prisma.statusDefinition.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StatusDefinitionUpdateArgs>(args: Prisma.SelectSubset<T, StatusDefinitionUpdateArgs<ExtArgs>>): Prisma.Prisma__StatusDefinitionClient<runtime.Types.Result.GetResult<Prisma.$StatusDefinitionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StatusDefinitions.
   * @param {StatusDefinitionDeleteManyArgs} args - Arguments to filter StatusDefinitions to delete.
   * @example
   * // Delete a few StatusDefinitions
   * const { count } = await prisma.statusDefinition.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StatusDefinitionDeleteManyArgs>(args?: Prisma.SelectSubset<T, StatusDefinitionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StatusDefinitions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StatusDefinitionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StatusDefinitions
   * const statusDefinition = await prisma.statusDefinition.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StatusDefinitionUpdateManyArgs>(args: Prisma.SelectSubset<T, StatusDefinitionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StatusDefinitions and returns the data updated in the database.
   * @param {StatusDefinitionUpdateManyAndReturnArgs} args - Arguments to update many StatusDefinitions.
   * @example
   * // Update many StatusDefinitions
   * const statusDefinition = await prisma.statusDefinition.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more StatusDefinitions and only return the `id`
   * const statusDefinitionWithIdOnly = await prisma.statusDefinition.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StatusDefinitionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StatusDefinitionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StatusDefinitionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one StatusDefinition.
   * @param {StatusDefinitionUpsertArgs} args - Arguments to update or create a StatusDefinition.
   * @example
   * // Update or create a StatusDefinition
   * const statusDefinition = await prisma.statusDefinition.upsert({
   *   create: {
   *     // ... data to create a StatusDefinition
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StatusDefinition we want to update
   *   }
   * })
   */
  upsert<T extends StatusDefinitionUpsertArgs>(args: Prisma.SelectSubset<T, StatusDefinitionUpsertArgs<ExtArgs>>): Prisma.Prisma__StatusDefinitionClient<runtime.Types.Result.GetResult<Prisma.$StatusDefinitionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StatusDefinitions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StatusDefinitionCountArgs} args - Arguments to filter StatusDefinitions to count.
   * @example
   * // Count the number of StatusDefinitions
   * const count = await prisma.statusDefinition.count({
   *   where: {
   *     // ... the filter for the StatusDefinitions we want to count
   *   }
   * })
  **/
  count<T extends StatusDefinitionCountArgs>(
    args?: Prisma.Subset<T, StatusDefinitionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StatusDefinitionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StatusDefinition.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StatusDefinitionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StatusDefinitionAggregateArgs>(args: Prisma.Subset<T, StatusDefinitionAggregateArgs>): Prisma.PrismaPromise<GetStatusDefinitionAggregateType<T>>

  /**
   * Group by StatusDefinition.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StatusDefinitionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StatusDefinitionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StatusDefinitionGroupByArgs['orderBy'] }
      : { orderBy?: StatusDefinitionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StatusDefinitionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStatusDefinitionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StatusDefinition model
 */
readonly fields: StatusDefinitionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StatusDefinition.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StatusDefinitionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StatusDefinition model
 */
export interface StatusDefinitionFieldRefs {
  readonly id: Prisma.FieldRef<"StatusDefinition", 'String'>
  readonly name: Prisma.FieldRef<"StatusDefinition", 'String'>
  readonly type: Prisma.FieldRef<"StatusDefinition", 'String'>
  readonly isActive: Prisma.FieldRef<"StatusDefinition", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"StatusDefinition", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"StatusDefinition", 'DateTime'>
}
    

// Custom InputTypes
/**
 * StatusDefinition findUnique
 */
export type StatusDefinitionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StatusDefinition
   */
  select?: Prisma.StatusDefinitionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StatusDefinition
   */
  omit?: Prisma.StatusDefinitionOmit<ExtArgs> | null
  /**
   * Filter, which StatusDefinition to fetch.
   */
  where: Prisma.StatusDefinitionWhereUniqueInput
}

/**
 * StatusDefinition findUniqueOrThrow
 */
export type StatusDefinitionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StatusDefinition
   */
  select?: Prisma.StatusDefinitionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StatusDefinition
   */
  omit?: Prisma.StatusDefinitionOmit<ExtArgs> | null
  /**
   * Filter, which StatusDefinition to fetch.
   */
  where: Prisma.StatusDefinitionWhereUniqueInput
}

/**
 * StatusDefinition findFirst
 */
export type StatusDefinitionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StatusDefinition
   */
  select?: Prisma.StatusDefinitionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StatusDefinition
   */
  omit?: Prisma.StatusDefinitionOmit<ExtArgs> | null
  /**
   * Filter, which StatusDefinition to fetch.
   */
  where?: Prisma.StatusDefinitionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StatusDefinitions to fetch.
   */
  orderBy?: Prisma.StatusDefinitionOrderByWithRelationInput | Prisma.StatusDefinitionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StatusDefinitions.
   */
  cursor?: Prisma.StatusDefinitionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StatusDefinitions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StatusDefinitions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StatusDefinitions.
   */
  distinct?: Prisma.StatusDefinitionScalarFieldEnum | Prisma.StatusDefinitionScalarFieldEnum[]
}

/**
 * StatusDefinition findFirstOrThrow
 */
export type StatusDefinitionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StatusDefinition
   */
  select?: Prisma.StatusDefinitionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StatusDefinition
   */
  omit?: Prisma.StatusDefinitionOmit<ExtArgs> | null
  /**
   * Filter, which StatusDefinition to fetch.
   */
  where?: Prisma.StatusDefinitionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StatusDefinitions to fetch.
   */
  orderBy?: Prisma.StatusDefinitionOrderByWithRelationInput | Prisma.StatusDefinitionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StatusDefinitions.
   */
  cursor?: Prisma.StatusDefinitionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StatusDefinitions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StatusDefinitions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StatusDefinitions.
   */
  distinct?: Prisma.StatusDefinitionScalarFieldEnum | Prisma.StatusDefinitionScalarFieldEnum[]
}

/**
 * StatusDefinition findMany
 */
export type StatusDefinitionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StatusDefinition
   */
  select?: Prisma.StatusDefinitionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StatusDefinition
   */
  omit?: Prisma.StatusDefinitionOmit<ExtArgs> | null
  /**
   * Filter, which StatusDefinitions to fetch.
   */
  where?: Prisma.StatusDefinitionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StatusDefinitions to fetch.
   */
  orderBy?: Prisma.StatusDefinitionOrderByWithRelationInput | Prisma.StatusDefinitionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StatusDefinitions.
   */
  cursor?: Prisma.StatusDefinitionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StatusDefinitions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StatusDefinitions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StatusDefinitions.
   */
  distinct?: Prisma.StatusDefinitionScalarFieldEnum | Prisma.StatusDefinitionScalarFieldEnum[]
}

/**
 * StatusDefinition create
 */
export type StatusDefinitionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StatusDefinition
   */
  select?: Prisma.StatusDefinitionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StatusDefinition
   */
  omit?: Prisma.StatusDefinitionOmit<ExtArgs> | null
  /**
   * The data needed to create a StatusDefinition.
   */
  data: Prisma.XOR<Prisma.StatusDefinitionCreateInput, Prisma.StatusDefinitionUncheckedCreateInput>
}

/**
 * StatusDefinition createMany
 */
export type StatusDefinitionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StatusDefinitions.
   */
  data: Prisma.StatusDefinitionCreateManyInput | Prisma.StatusDefinitionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StatusDefinition createManyAndReturn
 */
export type StatusDefinitionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StatusDefinition
   */
  select?: Prisma.StatusDefinitionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StatusDefinition
   */
  omit?: Prisma.StatusDefinitionOmit<ExtArgs> | null
  /**
   * The data used to create many StatusDefinitions.
   */
  data: Prisma.StatusDefinitionCreateManyInput | Prisma.StatusDefinitionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StatusDefinition update
 */
export type StatusDefinitionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StatusDefinition
   */
  select?: Prisma.StatusDefinitionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StatusDefinition
   */
  omit?: Prisma.StatusDefinitionOmit<ExtArgs> | null
  /**
   * The data needed to update a StatusDefinition.
   */
  data: Prisma.XOR<Prisma.StatusDefinitionUpdateInput, Prisma.StatusDefinitionUncheckedUpdateInput>
  /**
   * Choose, which StatusDefinition to update.
   */
  where: Prisma.StatusDefinitionWhereUniqueInput
}

/**
 * StatusDefinition updateMany
 */
export type StatusDefinitionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StatusDefinitions.
   */
  data: Prisma.XOR<Prisma.StatusDefinitionUpdateManyMutationInput, Prisma.StatusDefinitionUncheckedUpdateManyInput>
  /**
   * Filter which StatusDefinitions to update
   */
  where?: Prisma.StatusDefinitionWhereInput
  /**
   * Limit how many StatusDefinitions to update.
   */
  limit?: number
}

/**
 * StatusDefinition updateManyAndReturn
 */
export type StatusDefinitionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StatusDefinition
   */
  select?: Prisma.StatusDefinitionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StatusDefinition
   */
  omit?: Prisma.StatusDefinitionOmit<ExtArgs> | null
  /**
   * The data used to update StatusDefinitions.
   */
  data: Prisma.XOR<Prisma.StatusDefinitionUpdateManyMutationInput, Prisma.StatusDefinitionUncheckedUpdateManyInput>
  /**
   * Filter which StatusDefinitions to update
   */
  where?: Prisma.StatusDefinitionWhereInput
  /**
   * Limit how many StatusDefinitions to update.
   */
  limit?: number
}

/**
 * StatusDefinition upsert
 */
export type StatusDefinitionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StatusDefinition
   */
  select?: Prisma.StatusDefinitionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StatusDefinition
   */
  omit?: Prisma.StatusDefinitionOmit<ExtArgs> | null
  /**
   * The filter to search for the StatusDefinition to update in case it exists.
   */
  where: Prisma.StatusDefinitionWhereUniqueInput
  /**
   * In case the StatusDefinition found by the `where` argument doesn't exist, create a new StatusDefinition with this data.
   */
  create: Prisma.XOR<Prisma.StatusDefinitionCreateInput, Prisma.StatusDefinitionUncheckedCreateInput>
  /**
   * In case the StatusDefinition was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StatusDefinitionUpdateInput, Prisma.StatusDefinitionUncheckedUpdateInput>
}

/**
 * StatusDefinition delete
 */
export type StatusDefinitionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StatusDefinition
   */
  select?: Prisma.StatusDefinitionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StatusDefinition
   */
  omit?: Prisma.StatusDefinitionOmit<ExtArgs> | null
  /**
   * Filter which StatusDefinition to delete.
   */
  where: Prisma.StatusDefinitionWhereUniqueInput
}

/**
 * StatusDefinition deleteMany
 */
export type StatusDefinitionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StatusDefinitions to delete
   */
  where?: Prisma.StatusDefinitionWhereInput
  /**
   * Limit how many StatusDefinitions to delete.
   */
  limit?: number
}

/**
 * StatusDefinition without action
 */
export type StatusDefinitionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StatusDefinition
   */
  select?: Prisma.StatusDefinitionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StatusDefinition
   */
  omit?: Prisma.StatusDefinitionOmit<ExtArgs> | null
}
