
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  AdminUser: 'AdminUser',
  Company: 'Company',
  Contact: 'Contact',
  Lead: 'Lead',
  Project: 'Project',
  Activity: 'Activity',
  StatusDefinition: 'StatusDefinition',
  ImportBatch: 'ImportBatch'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const AdminUserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  password: 'password',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AdminUserScalarFieldEnum = (typeof AdminUserScalarFieldEnum)[keyof typeof AdminUserScalarFieldEnum]


export const CompanyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  industry: 'industry',
  address: 'address',
  website: 'website',
  email: 'email',
  phone: 'phone',
  status: 'status',
  notes: 'notes',
  source: 'source',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CompanyScalarFieldEnum = (typeof CompanyScalarFieldEnum)[keyof typeof CompanyScalarFieldEnum]


export const ContactScalarFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  firstName: 'firstName',
  lastName: 'lastName',
  position: 'position',
  email: 'email',
  mobile: 'mobile',
  landline: 'landline',
  contactPreference: 'contactPreference',
  status: 'status',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ContactScalarFieldEnum = (typeof ContactScalarFieldEnum)[keyof typeof ContactScalarFieldEnum]


export const LeadScalarFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  contactId: 'contactId',
  source: 'source',
  industry: 'industry',
  status: 'status',
  priority: 'priority',
  estimatedValue: 'estimatedValue',
  lastContactDate: 'lastContactDate',
  nextFollowUp: 'nextFollowUp',
  assignedTo: 'assignedTo',
  notes: 'notes',
  dateAdded: 'dateAdded',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type LeadScalarFieldEnum = (typeof LeadScalarFieldEnum)[keyof typeof LeadScalarFieldEnum]


export const ProjectScalarFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  projectName: 'projectName',
  projectLocation: 'projectLocation',
  projectType: 'projectType',
  status: 'status',
  contactId: 'contactId',
  assignedTo: 'assignedTo',
  source: 'source',
  quotationDate: 'quotationDate',
  startDate: 'startDate',
  targetCompletion: 'targetCompletion',
  actualCompletion: 'actualCompletion',
  installationStatus: 'installationStatus',
  testingStatus: 'testingStatus',
  commissioningStatus: 'commissioningStatus',
  remarks: 'remarks',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProjectScalarFieldEnum = (typeof ProjectScalarFieldEnum)[keyof typeof ProjectScalarFieldEnum]


export const ActivityScalarFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  projectId: 'projectId',
  contactId: 'contactId',
  type: 'type',
  date: 'date',
  time: 'time',
  performedBy: 'performedBy',
  contactPerson: 'contactPerson',
  description: 'description',
  result: 'result',
  nextAction: 'nextAction',
  nextFollowUp: 'nextFollowUp',
  notes: 'notes',
  createdAt: 'createdAt'
} as const

export type ActivityScalarFieldEnum = (typeof ActivityScalarFieldEnum)[keyof typeof ActivityScalarFieldEnum]


export const StatusDefinitionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StatusDefinitionScalarFieldEnum = (typeof StatusDefinitionScalarFieldEnum)[keyof typeof StatusDefinitionScalarFieldEnum]


export const ImportBatchScalarFieldEnum = {
  id: 'id',
  filename: 'filename',
  sheetName: 'sheetName',
  totalRows: 'totalRows',
  importedRows: 'importedRows',
  skippedRows: 'skippedRows',
  errorRows: 'errorRows',
  status: 'status',
  errors: 'errors',
  createdAt: 'createdAt'
} as const

export type ImportBatchScalarFieldEnum = (typeof ImportBatchScalarFieldEnum)[keyof typeof ImportBatchScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

